USE parkinsons;

DROP TABLE IF EXISTS GPS_AGG;
DROP TABLE IF EXISTS GPS;
DROP TABLE IF EXISTS Subject;

CREATE TABLE Subject (
	name VARCHAR(16),
	parkinsons TINYINT(1) NOT NULL,
	male TINYINT(1) NOT NULL,
	age INT(3) NOT NULL,
	ageDiagnosed INT(3) DEFAULT NULL,
	CONSTRAINT PRIMARY KEY (name)
) ENGINE=InnoDB;

CREATE TABLE GPS (
	name VARCHAR(16),
	diffSecs DOUBLE NOT NULL,
	latitude DOUBLE NOT NULL,
	longitude DOUBLE NOT NULL,
	altitude DOUBLE NOT NULL,
	time DATETIME NOT NULL,
	CONSTRAINT PRIMARY KEY (name, time),
	CONSTRAINT FOREIGN KEY (name) REFERENCES Subject (name) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE GPS_AGG (
	name VARCHAR(16),
	parkinsons TINYINT(1),
	day DATE NOT NULL,
	total DOUBLE NOT NULL,
	radius DOUBLE NOT NULL,
	CONSTRAINT PRIMARY KEY (name, day),
	CONSTRAINT FOREIGN KEY (name) REFERENCES Subject (name) ON DELETE CASCADE
) ENGINE=InnoDB;