DROP TABLE IF EXISTS GPS_AGG;
DROP TABLE IF EXISTS GPS;
DROP TABLE IF EXISTS Subject;

CREATE TABLE Subject (
	name VARCHAR(16) PRIMARY KEY,
	park TINYINT(1) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE GPS (
	name VARCHAR(16) PRIMARY KEY,
	# Flesh this out. diffSecs, Latitude, Longitude, Altitude, Day, Time
	CONSTRAINT FOREIGN KEY (name) REFERENCES Subject (name) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE GPS_AGG (
	name VARCHAR(16) PRIMARY KEY,
	day DATE NOT NULL,
	total DOUBLE NOT NULL,
	radius DOUBLE NOT NULL,
	CONSTRAINT FOREIGN KEY (name) REFERENCES Subject (name) ON DELETE CASCADE
) ENGINE=InnoDB;